project:
  type: website
  output-dir: docs

website:
  title: "Pranathi's Portfolio Website" 
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
        





