project:
  type: website
  output-dir: docs

website:
  title: "Pranathi Nagasai Andhe"

format:
  html:
    theme: none
    css: modern-style.css
    include-after-body:
      - text: |
          <script src="theme-toggle.js"></script>
